### ISSUE TITLE
GUI Crash + .png file not created in command line tool

### ISSUE THREAD

**Issue by studentism** [Skarsnik/SNESTilesKitten#1]
Not sure if I'm doing something fundamentally wrong, but I can't get the pre-compiled binaries to work for the life of me. The GUI crashes when I click "Refresh" after loading the ROM and entering the settings (or choosing a preset). The command line utility seems to be doing something, as it does include the correct number of tiles it should extract in the output, but never actually writes a .png file.

I know the ROM + addresses I'm using are fine. Just to confirm, I switched to a Zelda 3 ROM and tried to emulate the tutorial, entering all the given values manually, as well as trying the Link Sprites.stk preset that comes with the release. Same behavior. Here's the complete output of the command line utility, if it's of any help:

```
C:\Users\fyrab_000\Downloads\SNESTilesKitten.27.june.2019\SNESTilesKitten>SNESTinyKitten.exe --extract --png --rom "C:\Users\fyrab_000\Desktop\Legend of Zelda, The - A Link to the Past (USA).sfc" -o "C:\Users\fyrab_000\Downloads\out.png" "C:\Users\fyrab_000\Downloads\SNESTilesKitten.27.june.2019\SNESTilesKitten\Presets\The Legend of Zelda - Link Sprites.stk"
ROM has no header
ROM is LoROM
"C:/Users/fyrab_000/Desktop/Legend of Zelda, The - A Link to the Past (USA).sfc" is  "LoROM" false 1048576
ROM does not have SMC header
ROM type is LoROM
ROM Tile : THE LEGEND OF ZELDA
=Extracting tiles
=Loading rom  "C:/Users/fyrab_000/Desktop/Legend of Zelda, The - A Link to the Past (USA).sfc"
ROM has no header
ROM is LoROM
"C:/Users/fyrab_000/Desktop/Legend of Zelda, The - A Link to the Past (USA).sfc" is  "LoROM" false 1048576
1048576
Location "80000"
Size :  28672
896 tiles extracted
```

I'm on Windows 10. Tried replacing the Qt5 dlls to no effect. Appreciate any help you can offer.

**Comment by Skarsnik** [comment]
This is really weird, but I confirm that I get the same issue with the binary I released, I will look into this this week end :)

**Comment by Skarsnik** [comment]
Ok fixed with https://github.com/Skarsnik/SNESTilesKitten/releases/tag/11_august_2019

**Comment by studentism** [comment]
Thank you so much! Working perfectly now. (And thank you for all your time and effort in general; this is incredibly useful for getting tiles from other games into ALttPNG.) I'll go ahead and close this out.
