### ISSUE TITLE
Cannot compile on Ubuntu 21.04

### ISSUE THREAD

**Issue by hellocatfood** [Skarsnik/SNESTilesKitten#4]
I'm attempting to compile the software on Ubuntu 21.04. I've followed the instructions on the README and update the submodules, but when I run `qmake` nothing at all happens. no errors or messages are returned.

**Comment by Skarsnik** [comment]
I think qmake say nothing, try running make then

**Comment by hellocatfood** [comment]
Running `qmake` then `make` works, thanks. Might be worth adding this to the readme

**Comment by brainWave4** [comment]
What is the correct command to compile this on linux? I've tried `qmake SNESTilesKitten`, but I got the error output: `Cannot find file: SNESTilesKitten.`

Then I tried `qmake SNESTilesKitten.pro`, and there's no follow-up message whatsoever.

Next I've tried `make SNESTilesKitten` and I've got: `make: *** No rule to make target 'SNESTilesKitten'.  Stop.`

I thought I need to include the extension again. I've typed `make SNESTilesKitten.pro` and got the output: `make: Nothing to be done for 'SNESTilesKitten.pro'.`

**Comment by Skarsnik** [comment]
Just `make` after the qmake call

**Comment by brainWave4** [comment]
Here is the error message after calling `make`:
```
( test -e Makefile.Gui || /usr/lib/qt5/bin/qmake -o Makefile.Gui /home/****/Projects/snesTilesKitten/SNESTilesKitten/Gui.pro ) && make -f Makefile.Gui 
Project ERROR: Unknown module(s) in QT: core gui widgets
make: *** [Makefile:47: sub-Gui-pro-make_first-ordered] Error 3
```

**Comment by Skarsnik** [comment]
try qmake --version and join me on the qusb2snes discord https://discord.gg/NBMHd8Q2 so I can help you more :)

**Comment by brainWave4** [comment]
Following the discussion in discord, I need packages: `qtbase5-dev qt5-qmake qtchooser build-essential`

Then, opening terminal on the root folder, type:
```
mkdir build-dir; cd build-dir
qmake ../Gui.pro
make
```
The `make-dir` folder should then contain `SNESTilesKitten`.
